name: Trigger Site Rebuild on a CRON Schedule

on:
  schedule:
    - cron: '1 * * * *'
jobs:
  build:
    name: Trigger Site Rebuild
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: "erdem"
