ame: Workflow for checking http status codes

on:
  schedule:
    - cron: '1 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # ... uses ....
    - name: Check http status code of production site
http_response=$(curl -s -o response.txt -w "%{http_code}" http://deprem.francecentral.cloudapp.azure.com:8080/survey/questionlist2)
if [ $http_response != "200" ]; then
    echo "error"
else
    echo "OK"    
fi
    # ... uses ....
