name: test
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:
    name: test2
    runs-on: ubuntu-latest
    steps:
      - name: test3
      - run: echo "The job was automatically triggered by erdem a ${{ github.event_name }} event."
